# Base image.
FROM node:22.3.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8 

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./portfolio/package.json .

# Install packages.
RUN npm install

# Copy directory.
COPY ./portfolio .

# Document exposed port.
EXPOSE ${REACT_PORT}

# Start app.
CMD ["npm", "run", "dev"]